[package]
name = "uscope"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
petri = { path = "../petri" }
eframe = "0.27.2"
